name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-features --workspace -- -D warnings
          - command: test
            args: --color always
    steps:
      - name: Install XCB
        run: sudo apt install -y libxcb1-dev libxcb-randr0-dev libxcb-shm0-dev
      - uses: actions/checkout@v4
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
      - name: Run Command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
      - name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --allow-secret-key-import --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Sign Release
        run: gpg --batch --detach-sign "$GITHUB_WORKSPACE/target/release/i3lockr"
